spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

topic:
  order-created: test-order-created-topic
  payment-created: test-payment-created-topic
