spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/innowisedb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:false}
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8081

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:619296d21b477d598dc0dc0ec8eec349}
    access-expiration-ms: ${SECURITY_JWT_ACCESS_EXPIRATION_MS:900000}
    refresh-expiration-ms: ${SECURITY_JWT_REFRESH_EXPIRATION_MS:2592000000}