resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10

    instances:
      userService:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

spring:
  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: orderservice.kafka.event.PaymentCreatedEvent
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: ${topic.send-order}

  cache:
    type: redis
    redis:
      time-to-live: 10m
  data:
    redis:
      host: redis
      timeout: 2000ms
      port: 6379

topic:
  order-created: test-order-created-topic
  payment-created: payment-created-topic

security:
  jwt:
    secret: 619296d21b477d598dc0dc0ec8eec349
    access-expiration-ms: 900000
    refresh-expiration-ms: 2592000000
